name: "CLA"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
    
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        # Beta Release
        uses: contributor-assistant/github-action@v2.4.0
        env:
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          PERSONAL_ACCESS_TOKEN: ${{ secrets.BOT }}
        with:
          path-to-signatures: 'signatures-v2.json'
          path-to-document: 'https://github.com/open-domains/register/blob/main/terms.md' # e.g. a CLA or a DCO document
          # branch should not be protected
          branch: 'main'
          allowlist: od-bot,bot*,Omxpro
          remote-organization-name: 'open-domains'
          remote-repository-name: 'cla'

      - name: add CLA signed
        uses: actions-ecosystem/action-add-labels@v1
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        with:
          labels: "CLA signed"
          github_token: ${{ steps.create_token.outputs.token }}

      - name: remove CLA required
        uses: actions-ecosystem/action-remove-labels@v1
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        with:
          labels: "CLA Required"
          github_token: ${{ steps.create_token.outputs.token }}    

      - if: ${{ failure() }}
        name: Add CLA required
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "CLA Required"
          github_token: ${{ steps.create_token.outputs.token }}
          

        
