name: Check

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review, review_requested] # https://bit.ly/3FEj9D4
    branches: [master, main]

jobs:
  check-user-star:
    name: Check Star
    runs-on: ubuntu-latest
    steps:
      - {uses: gacts/is-stargazer@v1, with: {username: '${{ github.event.pull_request.user.login }}'}, id: check-star}

      - if: steps.check-star.outputs.is-stargazer != 'true'
        uses: actions/github-script@v6
        with:
          script: core.setFailed('â­ Please star this repository!')

#   checklist:
#     name: Checklist
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       pull-requests: write
#     steps:
#       - uses: thollander/actions-comment-pull-request@v1
#         with:
#           message: |
#             Your PR has been created! Please now wait for a maintainer to approve it.

#             > ### Made a mistake in the record?
#             >
#             > Don't worry, you can edit the changes in your repo and they should automatically be added to this PR.

#             Please, make sure that your PR passes the following checklist:

#             - â­ You have starred this repository
#             - ğŸ—’ The file with your subdomain has a `.json` extension and is formatted (indent size - 2 spaces).
#             - ğŸ‘¤ There is sufficient information in the `owner` field.
#             - ğŸ“‹ You have clearly described a reason for the domain registration (and what you plan to use it for) in the pull request's description
#             - ğŸ”— The website is reachable and a link to it is in the pull request description
#             - âœ… All CI checks have passed

#             <!--ID:CHECKLIST-->
#           comment_includes: <!--ID:CHECKLIST-->
