name: Star

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review, review_requested] # https://bit.ly/3FEj9D4
    branches: [main]

jobs:
  check-user-star:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - {uses: gacts/is-stargazer@v1, with: {username: '${{ github.event.pull_request.user.login }}'}, id: check-star}

      - if: steps.check-star.outputs.is-stargazer != 'true'
        uses: actions/github-script@v6
        with:
          script: core.setFailed('‚≠ê Please star this repository!')
